name: Maven Build + FCLI Setup

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  # -----------------------------
  # JOB 1: Maven Build
  # -----------------------------
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Verify Java & Maven
        run: |
          java -version
          mvn -version

      - name: Build Project
        run: |
          mvn clean install -DskipTests


  # -----------------------------
  # JOB 2: FCLI Installation
  # -----------------------------
  fcli-setup:
    runs-on: ubuntu-latest

    steps:
      - name: Install FCLI
        run: |
          npx @fortify/setup env init --tools=fcli:auto
          eval "$(npx @fortify/setup env shell)"

      - name: Verify FCLI Version
        run: |
          fcli --version
